# Задание 1

Генерация данных:

Создать DataFrame с полями: Дата, UserID, Продукт, Количество, Цена.

Данные для поля Продукт генерируются из списка возможных товаров ( не меньше 5 товаров )

Количество и Цена должны генерироваться случайно в заданных пределах.

Дата должна быть в пределах последнего года.

UserID представляет собой случайное число, имитирующее идентификаторы пользователей.

Обратите внимание, что должна быть возможности изменять количество сгенерированных строк. Минимальное количество - 1000 строк.

Сохранение данных:

Сохранить сгенерированный DataFrame в формате CSV для последующего анализа.

Результат выполнения задания (код генерации синтетических данных и созданный файл *.csv) необходимо выложить в github/gitlab и указать ссылку на Ваш репозиторий (не забудьте: репозиторий должен быть публичным).

In [1]:
!pip -q install pyspark
!pip -q install install-jdk
!pip -q install findspark

In [2]:
import pandas as pd
import numpy as np
import pyspark
import random
import datetime

In [3]:
pyspark.__version__

'3.5.3'

In [4]:
from pyspark.sql import SparkSession
# from pyspark.sql.functions import col, mean as mean_, countDistinct, count as count_, max as max_

In [5]:
spark = (SparkSession
    .builder
    .master('local[*]')
    .appName('leshakot')
    .getOrCreate()
    )

In [6]:
# Создать DataFrame с полями: Дата, UserID, Продукт, Количество, Цена.
np.random.seed(42)
# количество строк
count = 1000

product= ["молоко", "кефир", "хлеб", "курица", "свинина", "говядина", "яйцо", "помидор", "лук"]
year = 2024

id = list(range(1, count + 1))
products = [random.choice(product) for _ in range(count)]
price = [random.randint(100, 5000) for _ in range(count)]
quantities = [random.randint(1, 10) for _ in range(count)]
dates = [datetime.date(year, random.randint(1, 12), random.randint(1, 28)) for _ in range(count)]

columns = ['date', 'user_id', 'product', 'quantities', 'price']
df = spark.createDataFrame(list(zip(dates, id, products, quantities, price)), columns)

df.limit(5).toPandas()

         date  user_id product  quantities  price
0  2024-02-12        1    хлеб           6   4629
1  2024-07-01        2  курица           3   1520
2  2024-01-05        3     лук           2   1213
3  2024-09-11        4    хлеб           7   2542
4  2024-08-16        5  курица           2    130

In [7]:
# Сохранить сгенерированный DataFrame в формате CSV для последующего анализа.
df.toPandas().to_csv('sales.csv', header=True, index=False)

In [8]:
t = pd.read_csv('sales.csv')
t.sample(5)

           date  user_id product  quantities  price
521  2024-08-20      522  молоко           4   1683
737  2024-04-24      738    хлеб           4    106
740  2024-02-18      741    яйцо           2   2342
660  2024-11-26      661  молоко           4   4025
411  2024-10-07      412  курица           2   3263

In [9]:
spark.stop()